// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc_ewlm4gvppT-ulVs6Om3N_Ri7GleMnI',
    appId: '1:151912156719:web:9fb0743302c11405e000da',
    messagingSenderId: '151912156719',
    projectId: 'family-tracker-app-d79c8',
    authDomain: 'family-tracker-app-d79c8.firebaseapp.com',
    databaseURL: 'https://family-tracker-app-d79c8-default-rtdb.firebaseio.com',
    storageBucket: 'family-tracker-app-d79c8.appspot.com',
    measurementId: 'G-YQD23J6L9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuMcAugJm0sK9EGSzh7GI1bRDP3MQS7b4',
    appId: '1:151912156719:android:5114fea2ef8c5a5be000da',
    messagingSenderId: '151912156719',
    projectId: 'family-tracker-app-d79c8',
    databaseURL: 'https://family-tracker-app-d79c8-default-rtdb.firebaseio.com',
    storageBucket: 'family-tracker-app-d79c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8EWno7vcFrO8V4O9H-TJwtQ9dbxmEkSY',
    appId: '1:151912156719:ios:dc6e6fe13b0f2b85e000da',
    messagingSenderId: '151912156719',
    projectId: 'family-tracker-app-d79c8',
    databaseURL: 'https://family-tracker-app-d79c8-default-rtdb.firebaseio.com',
    storageBucket: 'family-tracker-app-d79c8.appspot.com',
    iosClientId:
        '151912156719-673dnbdn9p1g2uur8ssj4aa08abee971.apps.googleusercontent.com',
    iosBundleId: 'com.example.gavinFindingGrandmaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8EWno7vcFrO8V4O9H-TJwtQ9dbxmEkSY',
    appId: '1:151912156719:ios:dc6e6fe13b0f2b85e000da',
    messagingSenderId: '151912156719',
    projectId: 'family-tracker-app-d79c8',
    databaseURL: 'https://family-tracker-app-d79c8-default-rtdb.firebaseio.com',
    storageBucket: 'family-tracker-app-d79c8.appspot.com',
    iosClientId:
        '151912156719-673dnbdn9p1g2uur8ssj4aa08abee971.apps.googleusercontent.com',
    iosBundleId: 'com.example.gavinFindingGrandmaApp',
  );
}
